### ISSUE TITLE
Jenkins stability 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#104]
Today we faced Disk space issue on Prod Jenkins. Jenkins log reported error as,

```
2020-10-15 08:41:07.188+0000 [id=50] WARNING hudson.model.Queue#save: Failed to write out the queue file /var/jenkins_home/queue.xml
java.io.IOException: Disk quota exceeded
```
Jenkins Home is mounted over nfs at /mnt/data1/releases/jenkins/jenkins-prod 

We found that there is enough disk space available on cortx-storage server. 
```
[root@ssc-vm-0125 jenkins_workspace]# df -Th | grep cortx-storage
cortx-storage.colo.seagate.com:/mnt/data1 nfs4 4.9T 3.1T 1.9T 62% /mnt/data1
[root@ssc-vm-0125 jenkins_workspace]#
```

While debugging this issue along with @gowthamchinna found that jenkins_home directory is consuming 100Gb space. 

```
[root@ssc-vm-0279 jenkins]# du -sh *
32G     jenkins-dev
100G    jenkins-prod
```

We are placing all our component artifacts at nfs mount and jenkins_home should be containing only configuration files.  It should not consume this much space. On investigation found that space is consumed to Jenkins job log files. I am cleaning up old log files. 

To avoid this in future for every Jenkins job we should enable log rotation,

![image](https://user-images.githubusercontent.com/63289460/96130839-13c05100-0f16-11eb-9834-e816be08cbe4.png)

**Comment by hessio** [comment]
@shailesh-vaidya what is the status of this issue?

**Comment by shailesh-vaidya** [comment]
@hessio - We are not seeing any issue due to disk space now. However recently we had to restart Jenkins due to slowness. Let's keep this open to track it.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28329. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Anmol Vijwani commented in Jira Server:

Already was taken care

**Comment by cortx-admin** [comment]
> Anmol Vijwani commented in Jira Server:

Already been taken care of

**Comment by cortx-admin** [comment]
> Anmol Vijwani commented in Jira Server:

Already been taken care of.

**Comment by cortx-admin** [comment]
> Anmol Vijwani commented in Jira Server:

Already been taken care of
