### ISSUE TITLE
CORTX-28330: Share OVA build process with community

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-re#108]
Can we share the scripts and documentations to allow community members to build their own OVA images from the source code?  If so, this would help the community a LOT because developers could have an easy way to test their changes.

**Comment by hessio** [comment]
@shailesh-vaidya @gauravchaudhari02 is it possible to provide instructions to build the OVA to the open source community? I think this would be a nice thing to provide to the community

**Comment by hessio** [comment]
Hi @shailesh-vaidya what is the status on this issue?

**Comment by shailesh-vaidya** [comment]
Hi @hessio  - This is possible now as https://github.com/Seagate/cortx-re is opensource now. We need to document steps to generate OVA though,  
@mukul-seagate11 Let's plan this in upcoming Sprints.

**Comment by hessio** [comment]
Ok thanks

**Comment by shailesh-vaidya** [comment]
closing issue as an obsolete
