### ISSUE TITLE
Need a VM for development

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-re#167]
The release VM (OVA) that we have currently is awesome for quick deployment and testing.  

However we also need a release VM (OVA) that is setup for development.  Such a VM should come bundled with all the build dependencies.

Anything else @andriytk ?

**Comment by hessio** [comment]
Can we close this issue based on this devvm we have available in  the motr repo https://github.com/Seagate/cortx-motr/releases/tag/ova-centos79

**Comment by andriytk** [comment]
See also https://github.com/Seagate/cortx-motr/pull/1355.

Here is also CentOS 8 based OVA - https://github.com/andriytk/cortx-motr/releases/tag/centos83ova.

**Comment by hessio** [comment]
Ok so it is ok to close this issue as we have this requirement?

Or should we wait until [Seagate/cortx-motr#1355](https://github.com/Seagate/cortx-motr/pull/1355) is merged?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28332. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Closing as as we have CentOS 8 based OVA - [https://github.com/andriytk/cortx-motr/releases/tag/centos83ova](https://github.com/andriytk/cortx-motr/releases/tag/centos83ova)  
 

and - Seagate/cortx-motr#1355

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed
