### ISSUE TITLE
Create Validate Target on Build Makefile

### ISSUE THREAD

**Issue by gowthamchinna** [Seagate/cortx-re#253]
As of now we are only doing workspace check in the build targets, in future if we require more validations then its suggested to create a generic validate target and reuse the same on each component build.

Build Makefile : https://github.com/seagate/cortx-re/blob/main/docker/cortx-build/Makefile

Ref : https://github.com/Seagate/cortx-re/pull/245

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28333. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
@shailesh-vaidya do you know the status of this issue? Can we close this issue?

**Comment by hessio** [comment]
Hi @shailesh-vaidya and @gowthamchinna what is the status of this issue?

**Comment by cortx-admin** [comment]
> Nitish Singh commented in Jira Server:

PR raised: https://github.com/Seagate/cortx-re/pull/1128

**Comment by cortx-admin** [comment]
> Nitish Singh commented in Jira Server:

Testing is hhalted due to rate-limit error: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/docker-image-ci/6/console

**Comment by cortx-admin** [comment]
> Nitish Singh commented in Jira Server:

PR raised & testing completed.

**Comment by cortx-admin** [comment]
> Nitish Singh commented in Jira Server:

PR approved.

**Comment by cortx-admin** [comment]
> Pankaj Borole commented in Jira Server:

Provided fix
