### ISSUE TITLE
Fetch interface name dynamically in OVA Process. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#277]
We should fetch system interface names dynamically instead of hardcoding them. As we observed that interface names change per OS template used. 

Refer - https://github.com/Seagate/cortx-re/pull/228#discussion_r575147344

**Comment by hessio** [comment]
Hi @shailesh-vaidya is this issue resolved since the PR is merged? or is this on the backlog?

**Comment by shailesh-vaidya** [comment]
@hessio We can mark this issue as closed. This is obsolete with the K8s environment as we are using a single network now.

**Comment by hessio** [comment]
ok thanks
