### ISSUE TITLE
Add validation to verify that Jenkins node is back online after reboot. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#315]
Yes,  ref - https://stackoverflow.com/a/44363489

_Originally posted by @gowthamchinna in https://github.com/Seagate/cortx-re/pull/310#discussion_r599269887_

**Comment by hessio** [comment]
It seems this issue has been resolved @shailesh-vaidya ?

**Comment by shailesh-vaidya** [comment]
@hessio - Yes. Can can close this issue.

**Comment by hessio** [comment]
ok thanks
