### ISSUE TITLE
Migrate CI from Jenkins to GitHub Actions. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#40]
To migrate CI workflow from Jenkins to GitHub actions we should discuss and finalize our approach on below tasks. Please add if anything is missed. I have added possible solutions for few tasks. Please review and add your suggestions. 

- [ ] **Motr, S3 and Hare pre-merge jobs**  - 
Motr pre-merge job runs on hardware. S3, Hare pre-merge jobs are executed on Cent-OS/RedHat virtual machines.  Currently GitHub only supports Ubuntu from Linux distribution family https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners  
       
    **Possible solution**   
1. Work with component team and use container envorinment for pre-merge jobs. 
2. Use self hosted runners. https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/

- [ ] **Integration Build Generation and location** - 
Cortx need to be deployed as full stack for all the features. Currently we build all components individually and generate integrated release build. Release build contains rpm's from all the components. We should define strategy to build component level rpm's and generate release build from them. We should also finalize location (GitHub Release nomenclature) to place them.

     **Possible solution**
     We can create GitHub actions in every component repository and place artifact's (generated rpm's) at component repository.  Component rpm's will be placed in component level GitHub releases. Release engineering repository will have GitHub action to collect all components rpm's, perform other steps (rpm-signing, dependency validation etc.) and place release build at [Release Engineering](https://github.com/Seagate/cortx-re) repository. 

- [ ] **Branch wise Release build generation and location** -
We are generating branch wise release builds and placing them in different directories of ci-storage. We need to plan for Release build structure to support branch wise releases.   

     **Possible solution**  
     Finalize Release name syntax and adopt it in GitHub releases. So that branch wise release's can be maintained. 

- [ ] **Third party packages** - 
We are using couple of third party packages which are not built by Seagate team. We are storing them in [ci-storage uploads](http://ci-storage.mero.colo.seagate.com/releases/eos/uploads/) directory. We will need to store them in GitHub release.

    **Possible solution**
    Create release named [uploads](https://github.com/Seagate/cortx-re/releases/tag/uploads) and use it in GitHub actions to download and install third party packages. 

- [ ] **Generic workflow to build component Docker images and rpm's**
We should develop and use standard workflow's to build component Docker images and rpm's.  This will help in debugging issues faster and support multiple OS and Kernel versions. 

     Created https://github.com/Seagate/cortx-re/issues/39 and https://github.com/Seagate/cortx-re/issues/27 for workflow related discussion. Please add your suggestions/reviews there.   

- [ ] **Automated notifications, validation and checks** -
Currently Jenkins has configured many automated notifications e.g.  Email notification, Add release build details as Jira comment,. We have also configured couple of validation checks to avoid deployment failures e.g. RPM validation and dependency check. Motr CI customization etc. We will need to plan them in GitHub Actions. 

CC:  @amolkongre  @johnbent  @mukul-seagate11  @gauravchaudhari02  @pujamudaliar @venkuppu-chn  @balajiramachandran-seagate

**Comment by hessio** [comment]
Hi @shailesh-vaidya can you provide an update on this issue please?

**Comment by shailesh-vaidya** [comment]
@hessio  We can close this issue. This was created to track Jenkins -> GitHub actions migration.

**Comment by hessio** [comment]
ok thanks :)
