### ISSUE TITLE
Email and other details for GPG key

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#440]
We are using cortx.application@seagate.com in GPG key metadata. This is not working mail-box and should be replaced. 
Other Metadata used can be found at - https://github.com/Seagate/cortx-re/blob/main/scripts/rpm-signing/genkey-batch 

We can use cortx-questions@seagate.com as mentioned in - https://github.com/Seagate/cortx/blob/main/SECURITY.md 

Please review and suggest email to be used.

**Comment by hessio** [comment]
@shailesh-vaidya and @johnbent am I ok to close this issue? Looks like the issue was resolved. I will close as the issue looks resolved and you can reopen if you need.
