### ISSUE TITLE
Add Instruction to downgrade kernel correctly

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-re#546]
Since CORTX motr only works for specific kernel version, could you please provide a guideline to downgrade the kernel correctly?
I am asking this because when I install Centos-7 on Chameleon cloud and Emulab cloud, it comes with default kernel (not the Motr compatible version), thus there are many problem/bugs I met to get it up and running. 
I believe many community also experience this issue.
Would be great if the guideline is shared in the main CORTX repo. Thanks!
cc: @shailesh-vaidya

**Comment by hessio** [comment]
Ok no worries, I am trying to clear out the backlog, and label issue for tracking internally, would you say this is on the backlog? or is there a scheduled fix for this issue?

**Comment by shailesh-vaidya** [comment]
@hessio  We have removed kernel dependency in cortx-build docker image now. Let me validate it once and then we can close this one.

**Comment by hessio** [comment]
Ok thank you @shailesh-vaidya :)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28336. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

We have moved to Kubernetes based deployment and hence CORTX is no more tied up with Kernel Version. We can use any OS (CentOS/Ubuntu) for K8s setup and Deploy CORTX on it. Host OS and Application image OS need not be the same as the Kubernetes layer.

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

This bug is no more valid with CORTX deployed on Kubernetes cluster

**Comment by cortx-admin** [comment]
> Shailesh Vaidya commented in Jira Server:

This bug is no more valid with CORTX deployed on Kubernetes cluster

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
