### ISSUE TITLE
Release Branch Pre-Merge Testing

### ISSUE THREAD

**Issue by gowthamchinna** [Seagate/cortx-re#69]
To maintain clean build in release branch we need to ensure build quality before new changes merged into release branch and this can be achieved by introducing CT (Continuous Testing) in the release branch pre merge pipeline (Multibranch pipeline)

Existing Multibranch Workflow : 

  -  RPM Build tested for all the pull request. 

Disadvantage

  - Only RPM Build is tested using this pipeline but component basic functionalities are not tested.

 

Suggested Workflow

  - Perform VM deployment on each pull request targeted to release branch. later sanity test and other functionality related tests can be added to this.

 - Configure GitHub Pull request status check (required) for the above. This allows merges can be performed only when VM deployment is success.

**Comment by hessio** [comment]
Hi @gowthamchinna  was this ever implemented ? What is the status on this issue?

**Comment by shailesh-vaidya** [comment]
Hi @hessio We can close this issue. We have implemented most of the features described in this issue.

**Comment by hessio** [comment]
ok thanks :)
