### ISSUE TITLE
Improve manual PR validation Jenkins pipelines

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#87]
Due to security issues we need to disable multi-branch job's for components. We have created have Jenkins pipelines with manual trigger for validation at http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/ 
However this will be additional step for Seagate developers also for PR. Currently Jenkins pipelines take repo url and branch names as input to trigger job.  

As discussed with @gowthamchinna . We can improve it further to make it easy. 

1. Explore https://github.com/jenkinsci/ghprb-plugin#github-pull-request-builder-plugin . It has functionalities like trigger by PR comment from specified person, Add approval before code cloning etc. 
2. We can add comment in PR after manually triggered job is complete. 
3. Just take PR url as input, clone code based on it and run test cases.

**Comment by hessio** [comment]
@shailesh-vaidya can you provide an update on this issue?

**Comment by shailesh-vaidya** [comment]
@hessio We can close this issue. We have implemented PR validation checks.

**Comment by hessio** [comment]
Ok thanks :)
