### ISSUE TITLE
Need to change our template asking for new third party software

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-re#985]
### Please describe the feature/improvement you would like to see added.

Here is what the questions should be:

- Purpose of using new SW ?
- Location of the source code of new opensource SW ?
- Did you evaluate existing SW and confirm they do not serve the purpose ? If yes, include the comparison. If no, why ?
- Who is building it or how it gets built ? If yes, Which component/rpm will it be included ? i.e. name of the rpm which includes SW.
- Download location of opensource software package ?
- Who will be supporting this package ?
- Is there a configuration required for this? Who will be configuring it ?
- Which component is responsible for deploying on nodes ?
- What is the licensing policy? 
- Are we modifying the software or just using it as-is?
- How are we interfacing with this software? (e.g. command-line, static link, python import, dynamic link, etc)

### Please explain why you think adding this feature/improvement is important.

Discussed this with @pmbickley and this is a better set of questions.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31083. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
